package com.hospital.model;

import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

import com.hospital.enums.Gender;
import com.hospital.enums.PatientType;
import com.hospital.exception.HospitalException;

/**
 * Patient entity.
 *  - Rule P1: unique Patient ID (generated by service)
 *  - Rule P2: name, age, gender, mobile mandatory
 *  - Rule P4: EMERGENCY patients can be registered with minimal info
 *  - Rule P5/P6: records cannot be deleted; medical history retained permanently
 *  - Rule P7: a patient can have multiple visits (we store them here)
 */
public class Patient {

    private final String id;
    private final String name;
    private final int age;
    private final Gender gender;
    private final String mobile;
    private final String address;
    private final PatientType type;
    private final LocalDateTime registeredAt;
    private final List<String> medicalHistory = new CopyOnWriteArrayList<>();
    private final List<Visit> visits = new CopyOnWriteArrayList<>();

    public Patient(String id, String name, int age, Gender gender, String mobile,
                   String address, PatientType type) {
        if (name == null || name.isBlank()) throw new HospitalException("Patient name is mandatory.");
        if (age <= 0)                       throw new HospitalException("Patient age must be > 0.");
        if (gender == null)                 throw new HospitalException("Gender is mandatory.");
        if (type != PatientType.EMERGENCY) {
            if (mobile == null || mobile.isBlank()) {
                throw new HospitalException("Mobile is mandatory for regular patients.");
            }
        }
        this.id = id;
        this.name = name;
        this.age = age;
        this.gender = gender;
        this.mobile = mobile;
        this.address = address;
        this.type = type;
        this.registeredAt = LocalDateTime.now();
    }

    public String getId()              { return id; }
    public String getName()            { return name; }
    public int getAge()                { return age; }
    public Gender getGender()          { return gender; }
    public String getMobile()          { return mobile; }
    public String getAddress()         { return address; }
    public PatientType getType()       { return type; }
    public LocalDateTime getRegisteredAt() { return registeredAt; }
    public List<String> getMedicalHistory() { return Collections.unmodifiableList(medicalHistory); }
    public List<Visit> getVisits()     { return Collections.unmodifiableList(visits); }

    public void addMedicalNote(String note)  { medicalHistory.add(LocalDateTime.now() + " | " + note); }
    public void addVisit(Visit v)            { visits.add(v); }

    public boolean isEmergency() { return type == PatientType.EMERGENCY; }

    @Override
    public String toString() {
        return String.format("%s | %s | %d %s | %s | %s | %s",
                id, name, age, gender, mobile == null ? "-" : mobile, type, registeredAt);
    }
}
