package com.bank.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.locks.ReentrantLock;

import com.bank.exception.InsufficientBalanceException;
import com.bank.exception.InvalidAmountException;

/**
 * Abstract account.
 *  - Encapsulation : balance is private; modifications only via deposit/withdraw.
 *  - Abstraction   : subclasses (SavingsAccount, CurrentAccount) say WHAT kind of account.
 *  - Synchronization : every mutation goes through {@link #lock} so concurrent threads are safe.
 *
 * The {@link #lock} field is package-public via getLock() so the Bank service can
 * acquire it in a controlled order during transfers (deadlock prevention).
 */
public abstract class Account {

	private final String accountNumber;       // unique, auto-generated by Bank
	private final String accountHolder;
	private double balance;                   // ALWAYS access through lock
	private final List<Transaction> transactions = new ArrayList<>();
	private final ReentrantLock lock = new ReentrantLock();

	protected Account(String accountNumber, String accountHolder, double initialBalance) {
		this.accountNumber = accountNumber;
		this.accountHolder = accountHolder;
		this.balance = initialBalance;
		// initial deposit recorded as DEPOSIT
		this.transactions.add(new Transaction(Transaction.Type.DEPOSIT, initialBalance, initialBalance, null));
	}

	public abstract String getAccountType();

	public String getAccountNumber() { return accountNumber; }
	public String getAccountHolder() { return accountHolder; }

	/** Returns balance snapshot. Read under lock to avoid stale value. */
	public double getBalance() {
		lock.lock();
		try {
			return balance;
		} finally {
			lock.unlock();
		}
	}

	/** Read-only copy of the transaction history. */
	public List<Transaction> getTransactions() {
		lock.lock();
		try {
			return Collections.unmodifiableList(new ArrayList<>(transactions));
		} finally {
			lock.unlock();
		}
	}

	/** Exposed for Bank to do multi-account locked operations (transfer). */
	public ReentrantLock getLock() {
		return lock;
	}

	/**
	 * Deposit money into this account.
	 * Rule 2: amount must be positive.
	 */
	public void deposit(double amount) {
		if (amount <= 0) {
			throw new InvalidAmountException("Deposit amount must be positive. Got: " + amount);
		}
		lock.lock();
		try {
			balance += amount;
			transactions.add(new Transaction(Transaction.Type.DEPOSIT, amount, balance, null));
		} finally {
			lock.unlock();
		}
	}

	/**
	 * Withdraw money from this account.
	 * Rule 3: positive amount, Rule 4: balance must not go negative.
	 */
	public void withdraw(double amount) {
		if (amount <= 0) {
			throw new InvalidAmountException("Withdraw amount must be positive. Got: " + amount);
		}
		lock.lock();
		try {
			if (balance < amount) {
				throw new InsufficientBalanceException(
						"Insufficient balance in " + accountNumber + ". Available: Rs." + balance);
			}
			balance -= amount;
			transactions.add(new Transaction(Transaction.Type.WITHDRAW, amount, balance, null));
		} finally {
			lock.unlock();
		}
	}

	/**
	 * Internal helper used by Bank.transfer() AFTER both locks are held.
	 * NOTE: this method assumes the caller already holds this account's lock.
	 */
	public void debitForTransfer(double amount, String toAccount) {
		if (balance < amount) {
			throw new InsufficientBalanceException(
					"Insufficient balance in " + accountNumber + ". Available: Rs." + balance);
		}
		balance -= amount;
		transactions.add(new Transaction(Transaction.Type.TRANSFER_OUT, amount, balance, toAccount));
	}

	public void creditForTransfer(double amount, String fromAccount) {
		balance += amount;
		transactions.add(new Transaction(Transaction.Type.TRANSFER_IN, amount, balance, fromAccount));
	}

	@Override
	public String toString() {
		return String.format("%s [%s] - %s - Rs.%.2f", accountNumber, getAccountType(), accountHolder, getBalance());
	}
}
