package com.food.model;

import java.time.LocalDateTime;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.locks.ReentrantLock;

import com.food.enums.OrderStatus;
import com.food.enums.PaymentMode;
import com.food.exception.InvalidStatusTransitionException;

/**
 * Order entity.
 *  - id is unique (Rule 20) - generated by OrderService.
 *  - status transitions are validated (Rule 25, 26).
 *  - lock protects status / deliveryPartner mutations across threads.
 */
public class Order {

    private final String id;
    private final String customerId;
    private final String restaurantId;
    private final Map<String, Integer> items;          // menuItemId -> qty
    private final double subtotal;
    private final double tax;
    private final double deliveryCharge;
    private final double discount;
    private final double total;
    private final PaymentMode paymentMode;
    private final String idempotencyKey;
    private final LocalDateTime createdAt;

    private volatile OrderStatus status;
    private volatile String deliveryPartnerId;
    private volatile String paymentId;

    private final ReentrantLock lock = new ReentrantLock();

    public Order(String id, String customerId, String restaurantId,
                 Map<String, Integer> items, double subtotal, double tax,
                 double deliveryCharge, double discount, double total,
                 PaymentMode paymentMode, String idempotencyKey) {
        this.id = id;
        this.customerId = customerId;
        this.restaurantId = restaurantId;
        this.items = new LinkedHashMap<>(items);
        this.subtotal = subtotal;
        this.tax = tax;
        this.deliveryCharge = deliveryCharge;
        this.discount = discount;
        this.total = total;
        this.paymentMode = paymentMode;
        this.idempotencyKey = idempotencyKey;
        this.status = OrderStatus.PENDING_PAYMENT;
        this.createdAt = LocalDateTime.now();
    }

    public String getId()                 { return id; }
    public String getCustomerId()         { return customerId; }
    public String getRestaurantId()       { return restaurantId; }
    public Map<String, Integer> getItems(){ return Collections.unmodifiableMap(items); }
    public double getSubtotal()           { return subtotal; }
    public double getTax()                { return tax; }
    public double getDeliveryCharge()     { return deliveryCharge; }
    public double getDiscount()           { return discount; }
    public double getTotal()              { return total; }
    public PaymentMode getPaymentMode()   { return paymentMode; }
    public String getIdempotencyKey()     { return idempotencyKey; }
    public OrderStatus getStatus()        { return status; }
    public String getDeliveryPartnerId()  { return deliveryPartnerId; }
    public String getPaymentId()          { return paymentId; }
    public LocalDateTime getCreatedAt()   { return createdAt; }

    public void setPaymentId(String paymentId) { this.paymentId = paymentId; }
    public void setDeliveryPartnerId(String dp) { this.deliveryPartnerId = dp; }

    /** Move the order to a new status, validating the transition (Rule 25, 26). */
    public void transitionTo(OrderStatus next) {
        lock.lock();
        try {
            if (!status.canTransitionTo(next)) {
                throw new InvalidStatusTransitionException(
                        "Invalid transition: " + status + " -> " + next + " for order " + id);
            }
            this.status = next;
        } finally {
            lock.unlock();
        }
    }

    /** True if the order is still cancellable (before preparation starts - Rule 27). */
    public boolean isCancellable() {
        return status == OrderStatus.PENDING_PAYMENT || status == OrderStatus.CONFIRMED;
    }

    @Override
    public String toString() {
        return String.format("%s | cust=%s | rest=%s | items=%d | total=Rs.%.2f | %s | rider=%s",
                id, customerId, restaurantId, items.size(), total, status,
                deliveryPartnerId == null ? "-" : deliveryPartnerId);
    }
}
